// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4LJrBxdTSxsGvgDBvZwaUGAPnFVDZQOA',
    appId: '1:478869573918:web:4e9add5cddf2b8dd4ef90f',
    messagingSenderId: '478869573918',
    projectId: 'evde-ai',
    authDomain: 'evde-ai.firebaseapp.com',
    storageBucket: 'evde-ai.appspot.com',
    measurementId: 'G-GBJ5WPQMF5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgFKxSVM6Rb6Di_PD6cApj37a1b_Sa0CE',
    appId: '1:478869573918:android:752c6e2fea7d16894ef90f',
    messagingSenderId: '478869573918',
    projectId: 'evde-ai',
    storageBucket: 'evde-ai.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLOUaj8etx87DY6EdSofSSHGJm-P_NgmY',
    appId: '1:478869573918:ios:70981e4646f05ae84ef90f',
    messagingSenderId: '478869573918',
    projectId: 'evde-ai',
    storageBucket: 'evde-ai.appspot.com',
    iosBundleId: 'com.example.login',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLOUaj8etx87DY6EdSofSSHGJm-P_NgmY',
    appId: '1:478869573918:ios:70981e4646f05ae84ef90f',
    messagingSenderId: '478869573918',
    projectId: 'evde-ai',
    storageBucket: 'evde-ai.appspot.com',
    iosBundleId: 'com.example.login',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4LJrBxdTSxsGvgDBvZwaUGAPnFVDZQOA',
    appId: '1:478869573918:web:5d5e79ecdb1adf364ef90f',
    messagingSenderId: '478869573918',
    projectId: 'evde-ai',
    authDomain: 'evde-ai.firebaseapp.com',
    storageBucket: 'evde-ai.appspot.com',
    measurementId: 'G-E16CBXGZLZ',
  );

}